// Inlines the repo's brand SVGs into the bundle as data URIs.
// The Claude Design upload format ships no assets/ dir, so marks must be
// self-contained. Regenerated on every build — never hand-edit the output.
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const assets = join(here, '..', '..', 'assets');

const FORMS = {
  colorDark: 'sc-mark-color-dark.svg',
  colorLight: 'sc-mark-color-light.svg',
  monoCream: 'sc-mark-mono-cream.svg',
  monoInk: 'sc-mark-mono-ink.svg',
  avatarTile: 'sc-avatar-tile.svg',
  lockupCream: 'sc-lockup-cream.svg',
  lockupInk: 'sc-lockup-ink.svg',
};

const dataUri = (svg) =>
  'data:image/svg+xml,' +
  encodeURIComponent(svg.replace(/\s*\n\s*/g, ' ').trim())
    .replace(/%20/g, ' ')
    .replace(/'/g, '%27')
    .replace(/"/g, "'");

const entries = Object.entries(FORMS).map(([key, file]) => {
  const svg = readFileSync(join(assets, file), 'utf8');
  return `  ${key}: ${JSON.stringify(dataUri(svg))},`;
});

const out = `// GENERATED by scripts/gen-assets.mjs — do not edit.
// The SpicyChicken mark, inlined from assets/*.svg as data URIs.

/** The mark's available forms. */
export type MarkForm = ${Object.keys(FORMS).map((k) => `'${k}'`).join(' | ')};

/** Data-URI sources for every form of the SpicyChicken mark. */
export const SC_MARKS: Record<MarkForm, string> = {
${entries.join('\n')}
};
`;

writeFileSync(join(here, '..', 'src', 'marks.generated.ts'), out);
console.log(`gen-assets: inlined ${entries.length} marks (${(out.length / 1024).toFixed(1)}KB)`);
