// Generates the two build-time modules the wrappers import:
//   src/marks.generated.ts — the repo's brand SVGs inlined as data URIs (the
//     Claude Design upload format ships no assets/ dir, so marks must be
//     self-contained). One named export per form, plus the SC_MARKS object, so
//     a bundler can drop the forms a page never uses.
//   src/theme.generated.ts — build/theme.js verbatim as THEME_BOOT_SCRIPT, the
//     pre-paint snippet a page puts in <head> so ThemeToggle only reflects state.
// Both are regenerated on every build and gitignored — never hand-edit them.
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const repo = join(here, '..', '..');
const assets = join(repo, 'assets');
const src = join(here, '..', 'src');

const FORMS = {
  colorDark: 'sc-mark-color-dark.svg',
  colorLight: 'sc-mark-color-light.svg',
  monoCream: 'sc-mark-mono-cream.svg',
  monoInk: 'sc-mark-mono-ink.svg',
  avatarTile: 'sc-avatar-tile.svg',
  lockupCream: 'sc-lockup-cream.svg',
  lockupInk: 'sc-lockup-ink.svg',
};

// Double quotes become single quotes BEFORE encoding: encodeURIComponent leaves
// `'` alone but would turn `"` into `%22`, so this is what keeps the URIs short.
const dataUri = (svg) =>
  'data:image/svg+xml,' +
  encodeURIComponent(svg.replace(/\s*\n\s*/g, ' ').trim().replace(/"/g, "'")).replace(/%20/g, ' ');

const constName = (key) => 'MARK_' + key.replace(/([a-z])([A-Z])/g, '$1_$2').toUpperCase();

const forms = Object.entries(FORMS).map(([key, file]) => ({
  key,
  name: constName(key),
  uri: dataUri(readFileSync(join(assets, file), 'utf8')),
}));

const marks = `// GENERATED by scripts/gen-assets.mjs — do not edit.
// The SpicyChicken mark, inlined from assets/*.svg as data URIs.

/** The mark's available forms. */
export type MarkForm = ${forms.map((f) => `'${f.key}'`).join(' | ')};

${forms.map((f) => `/** Data-URI source for the \`${f.key}\` form of the mark. */\nexport const ${f.name} = ${JSON.stringify(f.uri)};`).join('\n\n')}

/** Data-URI sources for every form of the SpicyChicken mark, keyed by form. */
export const SC_MARKS: Record<MarkForm, string> = {
${forms.map((f) => `  ${f.key}: ${f.name},`).join('\n')}
};
`;
writeFileSync(join(src, 'marks.generated.ts'), marks);
console.log(`gen-assets: inlined ${forms.length} marks (${(marks.length / 1024).toFixed(1)}KB)`);

const themeJs = readFileSync(join(repo, 'build', 'theme.js'), 'utf8');
const theme = `// GENERATED by scripts/gen-assets.mjs from build/theme.js — do not edit.

/**
 * The pre-paint theme script (build/theme.js, verbatim). Put it in an inline
 * <script> in <head>, before the stylesheet paints: it applies the saved
 * \`sc-theme\` choice to \`data-theme\` so a pinned page never flashes, keeps
 * every \`.sc-theme-toggle\` in sync, and prints pinned-dark pages light.
 * With it in place \`ThemeToggle\` only reflects state; without it the toggle
 * applies the saved choice itself after mount.
 */
export const THEME_BOOT_SCRIPT: string = ${JSON.stringify(themeJs)};
`;
writeFileSync(join(src, 'theme.generated.ts'), theme);
console.log(`gen-assets: embedded build/theme.js as THEME_BOOT_SCRIPT (${(themeJs.length / 1024).toFixed(1)}KB)`);
